# Generated by Django 3.2.7 on 2021-09-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('employee_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('founder', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'graph_business',
            },
        ),
    ]
